### PR TITLE
adding timeout to monitor states

### PR DESCRIPTION
**Pull request by bfalacerda**
This is not thoroughly tested, just opening the pull request in case someone wants to use it at his own risk

### CODE REVIEW

**Comment by cdondrup** [comment]
Doesn't work:

```
Traceback (most recent call last):
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/scripts/long_term_patroller.py", line 126, in <module>
    l =  LongTermPatroller(waypoints_name, is_random, n_iterations)
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/scripts/long_term_patroller.py", line 37, in __init__
    n_iterations)
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/patroller.py", line 271, in __init__
    self._patroller = WaypointPatroller(waypoints_name, is_random, n_iterations)
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/patroller.py", line 181, in __init__
    self._high_level_move_base_patrol =  navigation.HighLevelMoveBase(False)
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/navigation.py", line 234, in __init__
    self._monitored_recoverable_move_base = MonitoredRecoverableMoveBase(going_to_charge)
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/navigation.py", line 147, in __init__
    self._battery_monitor = BatteryMonitor(going_to_charge)
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/src/waypoint_patroller/monitor_states.py", line 24, in __init__
    timeout=1200)
TypeError: __init__() got an unexpected keyword argument 'timeout'
[ INFO] [1385508278.277898665]: Subscribed to Topics: laser
[ INFO] [1385508278.293365092]: Requesting the map...

[ INFO] [1385508278.300924711]: Still waiting on map...

[INFO] [WallTime: 1385508278.361778] Tue Nov 26 23:24:38 [initandlisten] connection accepted from 127.0.0.1:44037 #6
[patroller-56] process has died [pid 23480, exit code 1, cmd /opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/scripts/long_term_patroller.py marathon2 false -1 __name:=patroller __log:=/localhome/pheidippides/.ros/log/3fccce2a-56f1-11e3-a9b4-843a4b7ee1a8/patroller-56.log].
log file: /localhome/pheidippides/.ros/log/3fccce2a-56f1-11e3-a9b4-843a4b7ee1a8/patroller-56*.log
```

**Comment by bfalacerda** [comment]
Did you update SMACH? I had to do some changes to it also. Anyway, the timeout is not properly implemented, I missed a detail when I was doing it. Just run the normal version, it's basically the same.

I'll close this to avoid confusion

**Comment by cdondrup** [comment]
It is too late to fix stuff. Yes, I forgot to update smach. Linda is now running with your and @cburbridge  code.

**Comment by bfalacerda** [comment]
that shouldn't be a big deal, what i added ended up being an if statement that's always false

**Pull request closed without merging**
