### PR TITLE
uses odom_mileage now

### PR DESCRIPTION
**Pull request by marc-hanheide**
this is now connecting to the new mileage topic implemented by @cdondrup I'm not sure if this should be pulled in by everybody, but we at UOL are going to use it now.

### CODE REVIEW

**Comment by hawesie** [comment]
Yeah, I'm a bit nervous about us all switching to this at this late stage. Is it an option we can switch on/off in configuration?

**Comment by cburbridge** [comment]
But we should all use the same. Id prefer to log both.

**Comment by marc-hanheide** [comment]
certainly, I'm not confident enough in this code to do it properly. Maybe @BFALacerda ?

**Comment by cdondrup** [comment]
Logging both would be a good alternative. We will try how it behaves over the weekend any ways.

**Comment by hawesie** [comment]
Agreed that we should all use the same, provided it works.

**Comment by cdondrup** [comment]
Difference over ~16 hours:
Mileage: 330710.0625
Odom Mileage: 342091.46875
Still happily running.

**Comment by marc-hanheide** [comment]
Anyone else switched to it? Has proven to be necessary and reliable for us.

**Comment by bfalacerda** [comment]
I'm finally merging this, it works. I'll make a pull request to merge it into hydro-devel also

**Comment by bfalacerda** [comment]
should I delete the odom_mileage branch?

**Pull request merged**
