### PR TITLE
catkinized patroller

### PR DESCRIPTION
**Pull request by bfalacerda**
```
Catkinized patroller package and added instructions on README on how to overlay the smach and navigation stacks with catkinized versions
```

### CODE REVIEW

**Comment by cdondrup** [comment]
When ever I try to build the navigation package like described in the readme I get something like:
`undefined reference to 'boost::thread::start_thread_noexcept()'` and
`undefined reference to 'boost::thread::join_noexcept()'` during linking for several modules. Any suggestions on how to fix this?

**Comment by bfalacerda** [comment]
I had some compiling errors (though not that one) when trying to compile 
in the wrong branch. The only suggestion I have is to double check that 
you are on the groovy-devel-catkinized branch

**Comment by hawesie** [comment]
In general these things can be fixed by editing the CMakeLists.txt for the module. You should add a find instructions for boost plus the components you require, e.g.

```
find_package(Boost REQUIRED COMPONENTS thread)
```

then link the target with the boost libraries, e.g.

```
target_link_libraries(base_local_planner ${Boost_LIBRARIES})
```

**Comment by hawesie** [comment]
That said, I built the navigation package from source following @BFALacerda's instructions last night, and it mostly worked, and OS X is usually very picky about linking. The changes I did need to make are in this pull request: https://github.com/ros-planning/navigation/pull/84

**Pull request merged**
