### PR TITLE
message dependencies generated before node

### PR DESCRIPTION
**Pull request by cburbridge**
On my new latop the strands desktop system would not compile because the messages were not generated on time in the very multithreaded build catkin uses. I found this:
http://answers.ros.org/question/52744/how-to-specify-dependencies-with-foo_msgs-catkin-packages/ 
which fixed it..

### CODE REVIEW

**Comment by bfalacerda** [comment]
That's strange, I didn't have these issues on my new laptop (exactly the same system supposedly). Anyway, I'll confirm if these changes don't cause problems for my laptop and for Bob on Monday and merge it then if everything's ok.

**Comment by marc-hanheide** [comment]
I have he same issue on our jenkins server. The build fails because the ap_msgs cannot be found. This is also a very fast machine. So I back Chris' request.

**Comment by cdondrup** [comment]
Won't commenting the line `find_package(scitos_apps_msgs COMPONENTS scitos_apps_msgs)` keep the map_saver from working with the joystick? Because if it isn't found the compilation flag won't be set. And why did you not comment that line in the waypoint_recorder CMakeLists?

**Comment by cburbridge** [comment]
Yes, that was wrong.

**Comment by cdondrup** [comment]
In that case I second your pull request.
I will also make the same changes to the scitos_teleop package which potentially faces the same issues because it doesn't specify the dependencies correctly.

**Pull request merged**
